spring:
  profiles:
    active: dev

logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: OFF
    org.springframework.cloud: DEBUG
    com.atsistemas: DEBUG
    
eureka:
  client:
    service-url:
      default-zone: http://localhost:8001/eureka
