server:
  port: 8080

logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: OFF
    org.springframework.cloud: ERROR
    com.atsistemas: ERROR

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

zuul:
  prefix: /api
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  ignored-services: '*'

