spring:
  profiles:
    active: dev

logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: OFF
    org.springframework.cloud: DEBUG
    com.atsistemas: DEBUG
